<?php
/**
 * RepricingItemOrderStatsDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  eSagu\EBay\RePricing\V1
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eSagu ebay RePricing API
 *
 * eSagu API to reprice items on ebay.
 *
<<<<<<< HEAD
 * OpenAPI spec version: 1.2.14
=======
 * OpenAPI spec version: 1.0.0
>>>>>>> a0d1cbe91759f3ab528e23040bc9b2ac6045ad7b
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace eSagu\EBay\RePricing\V1\Model;

use \ArrayAccess;

/**
 * RepricingItemOrderStatsDTO Class Doc Comment
 *
 * @category    Class
 * @description The repricing item&#39;s order stats.
 * @package     eSagu\EBay\RePricing\V1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RepricingItemOrderStatsDTO implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'RepricingItemOrderStatsDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
<<<<<<< HEAD
        'repricing_item_id' => 'int',
        'last_seven_days' => 'int',
        'last_fourteen_days' => 'int',
        'last_thirty_days' => 'int',
=======
        'last_fourteen_days' => 'int',
        'last_seven_days' => 'int',
        'last_thirty_days' => 'int',
        'repricing_item_id' => 'int',
>>>>>>> a0d1cbe91759f3ab528e23040bc9b2ac6045ad7b
        'inserted' => '\DateTime',
        'updated' => '\DateTime'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
<<<<<<< HEAD
        'repricing_item_id' => 'repricingItemId',
        'last_seven_days' => 'lastSevenDays',
        'last_fourteen_days' => 'lastFourteenDays',
        'last_thirty_days' => 'lastThirtyDays',
=======
        'last_fourteen_days' => 'lastFourteenDays',
        'last_seven_days' => 'lastSevenDays',
        'last_thirty_days' => 'lastThirtyDays',
        'repricing_item_id' => 'repricingItemId',
>>>>>>> a0d1cbe91759f3ab528e23040bc9b2ac6045ad7b
        'inserted' => 'inserted',
        'updated' => 'updated'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
<<<<<<< HEAD
        'repricing_item_id' => 'setRepricingItemId',
        'last_seven_days' => 'setLastSevenDays',
        'last_fourteen_days' => 'setLastFourteenDays',
        'last_thirty_days' => 'setLastThirtyDays',
=======
        'last_fourteen_days' => 'setLastFourteenDays',
        'last_seven_days' => 'setLastSevenDays',
        'last_thirty_days' => 'setLastThirtyDays',
        'repricing_item_id' => 'setRepricingItemId',
>>>>>>> a0d1cbe91759f3ab528e23040bc9b2ac6045ad7b
        'inserted' => 'setInserted',
        'updated' => 'setUpdated'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
<<<<<<< HEAD
        'repricing_item_id' => 'getRepricingItemId',
        'last_seven_days' => 'getLastSevenDays',
        'last_fourteen_days' => 'getLastFourteenDays',
        'last_thirty_days' => 'getLastThirtyDays',
=======
        'last_fourteen_days' => 'getLastFourteenDays',
        'last_seven_days' => 'getLastSevenDays',
        'last_thirty_days' => 'getLastThirtyDays',
        'repricing_item_id' => 'getRepricingItemId',
>>>>>>> a0d1cbe91759f3ab528e23040bc9b2ac6045ad7b
        'inserted' => 'getInserted',
        'updated' => 'getUpdated'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
<<<<<<< HEAD
        $this->container['repricing_item_id'] = isset($data['repricing_item_id']) ? $data['repricing_item_id'] : null;
        $this->container['last_seven_days'] = isset($data['last_seven_days']) ? $data['last_seven_days'] : null;
        $this->container['last_fourteen_days'] = isset($data['last_fourteen_days']) ? $data['last_fourteen_days'] : null;
        $this->container['last_thirty_days'] = isset($data['last_thirty_days']) ? $data['last_thirty_days'] : null;
=======
        $this->container['last_fourteen_days'] = isset($data['last_fourteen_days']) ? $data['last_fourteen_days'] : null;
        $this->container['last_seven_days'] = isset($data['last_seven_days']) ? $data['last_seven_days'] : null;
        $this->container['last_thirty_days'] = isset($data['last_thirty_days']) ? $data['last_thirty_days'] : null;
        $this->container['repricing_item_id'] = isset($data['repricing_item_id']) ? $data['repricing_item_id'] : null;
>>>>>>> a0d1cbe91759f3ab528e23040bc9b2ac6045ad7b
        $this->container['inserted'] = isset($data['inserted']) ? $data['inserted'] : null;
        $this->container['updated'] = isset($data['updated']) ? $data['updated'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
<<<<<<< HEAD
     * Gets repricing_item_id
     * @return int
     */
    public function getRepricingItemId()
    {
        return $this->container['repricing_item_id'];
    }

    /**
     * Sets repricing_item_id
     * @param int $repricing_item_id
     * @return $this
     */
    public function setRepricingItemId($repricing_item_id)
    {
        $this->container['repricing_item_id'] = $repricing_item_id;
=======
     * Gets last_fourteen_days
     * @return int
     */
    public function getLastFourteenDays()
    {
        return $this->container['last_fourteen_days'];
    }

    /**
     * Sets last_fourteen_days
     * @param int $last_fourteen_days
     * @return $this
     */
    public function setLastFourteenDays($last_fourteen_days)
    {
        $this->container['last_fourteen_days'] = $last_fourteen_days;
>>>>>>> a0d1cbe91759f3ab528e23040bc9b2ac6045ad7b

        return $this;
    }

    /**
     * Gets last_seven_days
     * @return int
     */
    public function getLastSevenDays()
    {
        return $this->container['last_seven_days'];
    }

    /**
     * Sets last_seven_days
     * @param int $last_seven_days
     * @return $this
     */
    public function setLastSevenDays($last_seven_days)
    {
        $this->container['last_seven_days'] = $last_seven_days;

        return $this;
    }

    /**
<<<<<<< HEAD
     * Gets last_fourteen_days
     * @return int
     */
    public function getLastFourteenDays()
    {
        return $this->container['last_fourteen_days'];
    }

    /**
     * Sets last_fourteen_days
     * @param int $last_fourteen_days
     * @return $this
     */
    public function setLastFourteenDays($last_fourteen_days)
    {
        $this->container['last_fourteen_days'] = $last_fourteen_days;

        return $this;
    }

    /**
=======
>>>>>>> a0d1cbe91759f3ab528e23040bc9b2ac6045ad7b
     * Gets last_thirty_days
     * @return int
     */
    public function getLastThirtyDays()
    {
        return $this->container['last_thirty_days'];
    }

    /**
     * Sets last_thirty_days
     * @param int $last_thirty_days
     * @return $this
     */
    public function setLastThirtyDays($last_thirty_days)
    {
        $this->container['last_thirty_days'] = $last_thirty_days;

        return $this;
    }

    /**
<<<<<<< HEAD
=======
     * Gets repricing_item_id
     * @return int
     */
    public function getRepricingItemId()
    {
        return $this->container['repricing_item_id'];
    }

    /**
     * Sets repricing_item_id
     * @param int $repricing_item_id
     * @return $this
     */
    public function setRepricingItemId($repricing_item_id)
    {
        $this->container['repricing_item_id'] = $repricing_item_id;

        return $this;
    }

    /**
>>>>>>> a0d1cbe91759f3ab528e23040bc9b2ac6045ad7b
     * Gets inserted
     * @return \DateTime
     */
    public function getInserted()
    {
        return $this->container['inserted'];
    }

    /**
     * Sets inserted
     * @param \DateTime $inserted
     * @return $this
     */
    public function setInserted($inserted)
    {
        $this->container['inserted'] = $inserted;

        return $this;
    }

    /**
     * Gets updated
     * @return \DateTime
     */
    public function getUpdated()
    {
        return $this->container['updated'];
    }

    /**
     * Sets updated
     * @param \DateTime $updated
     * @return $this
     */
    public function setUpdated($updated)
    {
        $this->container['updated'] = $updated;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\eSagu\EBay\RePricing\V1\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\eSagu\EBay\RePricing\V1\ObjectSerializer::sanitizeForSerialization($this));
    }
}


