<?php
/**
 * RepricingItemPriceUploadDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  eSagu\EBay\RePricing\V1
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eSagu ebay RePricing API
 *
 * eSagu API to reprice items on ebay.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace eSagu\EBay\RePricing\V1\Model;

use \ArrayAccess;

/**
 * RepricingItemPriceUploadDTO Class Doc Comment
 *
 * @category    Class
 * @description A price upload. Contains information about the price upload, to ebay via the trading API, like the ackType and an error code.
 * @package     eSagu\EBay\RePricing\V1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RepricingItemPriceUploadDTO implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'RepricingItemPriceUploadDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'ack_type' => 'string',
        'error_code' => 'int',
        'inserted' => '\DateTime',
        'message_id' => 'string',
        'updated' => '\DateTime',
        'uploaded_price' => 'int'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'ack_type' => 'ackType',
        'error_code' => 'errorCode',
        'inserted' => 'inserted',
        'message_id' => 'messageId',
        'updated' => 'updated',
        'uploaded_price' => 'uploadedPrice'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'ack_type' => 'setAckType',
        'error_code' => 'setErrorCode',
        'inserted' => 'setInserted',
        'message_id' => 'setMessageId',
        'updated' => 'setUpdated',
        'uploaded_price' => 'setUploadedPrice'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'ack_type' => 'getAckType',
        'error_code' => 'getErrorCode',
        'inserted' => 'getInserted',
        'message_id' => 'getMessageId',
        'updated' => 'getUpdated',
        'uploaded_price' => 'getUploadedPrice'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    const ACK_TYPE_CUSTOM_CODE = 'CUSTOM_CODE';
    const ACK_TYPE_FAILURE = 'FAILURE';
    const ACK_TYPE_PARTIAL_FAILURE = 'PARTIAL_FAILURE';
    const ACK_TYPE_SUCCESS = 'SUCCESS';
    const ACK_TYPE_WARNING = 'WARNING';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getAckTypeAllowableValues()
    {
        return [
            self::ACK_TYPE_CUSTOM_CODE,
            self::ACK_TYPE_FAILURE,
            self::ACK_TYPE_PARTIAL_FAILURE,
            self::ACK_TYPE_SUCCESS,
            self::ACK_TYPE_WARNING,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ack_type'] = isset($data['ack_type']) ? $data['ack_type'] : null;
        $this->container['error_code'] = isset($data['error_code']) ? $data['error_code'] : null;
        $this->container['inserted'] = isset($data['inserted']) ? $data['inserted'] : null;
        $this->container['message_id'] = isset($data['message_id']) ? $data['message_id'] : null;
        $this->container['updated'] = isset($data['updated']) ? $data['updated'] : null;
        $this->container['uploaded_price'] = isset($data['uploaded_price']) ? $data['uploaded_price'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        $allowed_values = ["CUSTOM_CODE", "FAILURE", "PARTIAL_FAILURE", "SUCCESS", "WARNING"];
        if (!in_array($this->container['ack_type'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'ack_type', must be one of 'CUSTOM_CODE', 'FAILURE', 'PARTIAL_FAILURE', 'SUCCESS', 'WARNING'.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        $allowed_values = ["CUSTOM_CODE", "FAILURE", "PARTIAL_FAILURE", "SUCCESS", "WARNING"];
        if (!in_array($this->container['ack_type'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets ack_type
     * @return string
     */
    public function getAckType()
    {
        return $this->container['ack_type'];
    }

    /**
     * Sets ack_type
     * @param string $ack_type
     * @return $this
     */
    public function setAckType($ack_type)
    {
        $allowed_values = array('CUSTOM_CODE', 'FAILURE', 'PARTIAL_FAILURE', 'SUCCESS', 'WARNING');
        if (!is_null($ack_type) && (!in_array($ack_type, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'ack_type', must be one of 'CUSTOM_CODE', 'FAILURE', 'PARTIAL_FAILURE', 'SUCCESS', 'WARNING'");
        }
        $this->container['ack_type'] = $ack_type;

        return $this;
    }

    /**
     * Gets error_code
     * @return int
     */
    public function getErrorCode()
    {
        return $this->container['error_code'];
    }

    /**
     * Sets error_code
     * @param int $error_code
     * @return $this
     */
    public function setErrorCode($error_code)
    {
        $this->container['error_code'] = $error_code;

        return $this;
    }

    /**
     * Gets inserted
     * @return \DateTime
     */
    public function getInserted()
    {
        return $this->container['inserted'];
    }

    /**
     * Sets inserted
     * @param \DateTime $inserted
     * @return $this
     */
    public function setInserted($inserted)
    {
        $this->container['inserted'] = $inserted;

        return $this;
    }

    /**
     * Gets message_id
     * @return string
     */
    public function getMessageId()
    {
        return $this->container['message_id'];
    }

    /**
     * Sets message_id
     * @param string $message_id
     * @return $this
     */
    public function setMessageId($message_id)
    {
        $this->container['message_id'] = $message_id;

        return $this;
    }

    /**
     * Gets updated
     * @return \DateTime
     */
    public function getUpdated()
    {
        return $this->container['updated'];
    }

    /**
     * Sets updated
     * @param \DateTime $updated
     * @return $this
     */
    public function setUpdated($updated)
    {
        $this->container['updated'] = $updated;

        return $this;
    }

    /**
     * Gets uploaded_price
     * @return int
     */
    public function getUploadedPrice()
    {
        return $this->container['uploaded_price'];
    }

    /**
     * Sets uploaded_price
     * @param int $uploaded_price
     * @return $this
     */
    public function setUploadedPrice($uploaded_price)
    {
        $this->container['uploaded_price'] = $uploaded_price;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\eSagu\EBay\RePricing\V1\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\eSagu\EBay\RePricing\V1\ObjectSerializer::sanitizeForSerialization($this));
    }
}


