<?php
/**
 * RepricingEbayOrderHistoryDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  eSagu\Ebay\RePricing\V1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eSagu ebay RePricing API
 *
 * eSagu API to reprice items on ebay.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace eSagu\Ebay\RePricing\V1;

/**
 * RepricingEbayOrderHistoryDTOTest Class Doc Comment
 *
 * @category    Class */
// * @description RepricingEbayOrderHistoryDTO
/**
 * @package     eSagu\Ebay\RePricing\V1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RepricingEbayOrderHistoryDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "RepricingEbayOrderHistoryDTO"
     */
    public function testRepricingEbayOrderHistoryDTO()
    {

    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {

    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {

    }

    /**
     * Test attribute "item_price_total"
     */
    public function testPropertyItemPriceTotal()
    {

    }

    /**
     * Test attribute "quantity_total"
     */
    public function testPropertyQuantityTotal()
    {

    }

}
