<?php
/**
 * RepricingItemPriceUploadDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  eSagu\Ebay\RePricing\V1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eSagu ebay RePricing API
 *
 * eSagu API to reprice items on ebay.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace eSagu\Ebay\RePricing\V1;

/**
 * RepricingItemPriceUploadDTOTest Class Doc Comment
 *
 * @category    Class */
// * @description A price upload. Contains information about the price upload, to ebay via the trading API, like the ackType and an error code.
/**
 * @package     eSagu\Ebay\RePricing\V1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RepricingItemPriceUploadDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "RepricingItemPriceUploadDTO"
     */
    public function testRepricingItemPriceUploadDTO()
    {

    }

    /**
     * Test attribute "ack_type"
     */
    public function testPropertyAckType()
    {

    }

    /**
     * Test attribute "error_code"
     */
    public function testPropertyErrorCode()
    {

    }

    /**
     * Test attribute "inserted"
     */
    public function testPropertyInserted()
    {

    }

    /**
     * Test attribute "message_id"
     */
    public function testPropertyMessageId()
    {

    }

    /**
     * Test attribute "updated"
     */
    public function testPropertyUpdated()
    {

    }

    /**
     * Test attribute "uploaded_price"
     */
    public function testPropertyUploadedPrice()
    {

    }

}
