<?php
/**
 * RepricingCSVRequestDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  eSagu\Ebay\RePricing\V1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eSagu ebay RePricing API
 *
 * eSagu API to reprice items on ebay.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace eSagu\Ebay\RePricing\V1;

/**
 * RepricingCSVRequestDTOTest Class Doc Comment
 *
 * @category    Class */
// * @description A CSV file export. A CSV file can be downloaded using the csvDownloadUrl when the state is DONE.
/**
 * @package     eSagu\Ebay\RePricing\V1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RepricingCSVRequestDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "RepricingCSVRequestDTO"
     */
    public function testRepricingCSVRequestDTO()
    {

    }

    /**
     * Test attribute "csv_download_url"
     */
    public function testPropertyCsvDownloadUrl()
    {

    }

    /**
     * Test attribute "exclude_expired_items"
     */
    public function testPropertyExcludeExpiredItems()
    {

    }

    /**
     * Test attribute "fields"
     */
    public function testPropertyFields()
    {

    }

    /**
     * Test attribute "number_format"
     */
    public function testPropertyNumberFormat()
    {

    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {

    }

}
