<?php
/**
 * SettingsDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  eSagu\Ebay\RePricing\V1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eSagu ebay RePricing API
 *
 * eSagu API to reprice items on ebay.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace eSagu\Ebay\RePricing\V1;

/**
 * SettingsDTOTest Class Doc Comment
 *
 * @category    Class */
// * @description SettingsDTO
/**
 * @package     eSagu\Ebay\RePricing\V1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SettingsDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "SettingsDTO"
     */
    public function testSettingsDTO()
    {

    }

    /**
     * Test attribute "crawl_quantity_zero_items"
     */
    public function testPropertyCrawlQuantityZeroItems()
    {

    }

    /**
     * Test attribute "download_enabled"
     */
    public function testPropertyDownloadEnabled()
    {

    }

    /**
     * Test attribute "ebay_global_id"
     */
    public function testPropertyEbayGlobalId()
    {

    }

    /**
     * Test attribute "item_max_age_seconds"
     */
    public function testPropertyItemMaxAgeSeconds()
    {

    }

    /**
     * Test attribute "outdated_stock_items_minus_days"
     */
    public function testPropertyOutdatedStockItemsMinusDays()
    {

    }

    /**
     * Test attribute "show_expert_settings"
     */
    public function testPropertyShowExpertSettings()
    {

    }

    /**
     * Test attribute "stock_update_max_age"
     */
    public function testPropertyStockUpdateMaxAge()
    {

    }

    /**
     * Test attribute "upload_enabled"
     */
    public function testPropertyUploadEnabled()
    {

    }

    /**
     * Test attribute "use_relist_parent_id"
     */
    public function testPropertyUseRelistParentId()
    {

    }

}
