<?php
/**
 * ItemStrategyApiTest
 * PHP version 5
 *
 * @category Class
 * @package  eSagu\Ebay\RePricing\V1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eSagu ebay RePricing API
 *
 * eSagu API to reprice items on ebay.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace eSagu\Ebay\RePricing\V1;

use \eSagu\Ebay\RePricing\V1\Configuration;
use \eSagu\Ebay\RePricing\V1\ApiClient;
use \eSagu\Ebay\RePricing\V1\ApiException;
use \eSagu\Ebay\RePricing\V1\ObjectSerializer;

/**
 * ItemStrategyApiTest Class Doc Comment
 *
 * @category Class
 * @package  eSagu\Ebay\RePricing\V1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ItemStrategyApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for get
     *
     * Gets the item's strategy settings specified by the repricing item id..
     *
     */
    public function testGet()
    {

    }

    /**
     * Test case for put
     *
     * Creates or updates the item's strategy settings..
     *
     */
    public function testPut()
    {

    }

}
